//Burger action identifiers
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS'
export const DEL_INGREDIENTS = 'DEL_INGREDIENTS'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

//Order action identifiers
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAILURE = 'PURCHASE_BURGER_FAILURE'
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASING = 'PURCHASING'
export const ORDER_START = 'ORDER_START'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAILURE = 'ORDER_FAILURE'

//Authentication action identifiers
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH'
